export const clientInfo = Object.freeze([
    {
      entityId: 1,
      clientCode: 'C001',
      company: 'Company A',
      externalId: 'EXT001',
      surname: 'Barnard',
      firstName: 'Dylan',
      dateOfBirth: '1985-01-01',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8501015800083',
      age: 38,
      drivingLicenceIssueDate: '2003-05-15',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class A',
      lastInteractionDate: '2023-09-05'
    },
    {
      entityId: 2,
      clientCode: 'C002',
      company: 'Company B',
      externalId: 'EXT002',
      surname: 'Yeatman',
      firstName: 'Candice',
      dateOfBirth: '1990-05-12',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9005120489087',
      age: 33,
      drivingLicenceIssueDate: '2010-08-21',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class B',
      lastInteractionDate: '2023-07-22'
    },
    {
      entityId: 3,
      clientCode: 'C003',
      company: 'Company C',
      externalId: 'EXT003',
      surname: 'Doe',
      firstName: 'John',
      dateOfBirth: '1979-01-04',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7901045069085',
      age: 44,
      drivingLicenceIssueDate: '1998-11-10',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class C',
      lastInteractionDate: '2023-03-15'
    },
    {
      entityId: 4,
      clientCode: 'C004',
      company: 'Company D',
      externalId: 'EXT004',
      surname: 'Croft',
      firstName: 'Lara',
      dateOfBirth: '1975-06-25',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7506254986081',
      age: 48,
      drivingLicenceIssueDate: '1994-12-08',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class D',
      lastInteractionDate: '2023-11-08'
    },
    {
      entityId: 5,
      clientCode: 'C005',
      company: 'Company E',
      externalId: 'EXT005',
      surname: 'Smith',
      firstName: 'James',
      dateOfBirth: '1988-02-07',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8802075043083',
      age: 35,
      drivingLicenceIssueDate: '2007-10-01',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class E',
      lastInteractionDate: '2023-10-01'
    },
    {
      entityId: 6,
      clientCode: 'C006',
      company: 'Company F',
      externalId: 'EXT006',
      surname: 'Davis',
      firstName: 'Emily',
      dateOfBirth: '1996-02-15',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9602150872089',
      age: 27,
      drivingLicenceIssueDate: '2015-06-19',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class F',
      lastInteractionDate: '2023-06-19'
    },
    {
      entityId: 7,
      clientCode: 'C007',
      company: 'Company G',
      externalId: 'EXT007',
      surname: 'Johnson',
      firstName: 'Michael',
      dateOfBirth: '1992-03-10',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9203105230081',
      age: 31,
      drivingLicenceIssueDate: '2010-04-11',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class G',
      lastInteractionDate: '2023-04-11'
    },
    {
      entityId: 8,
      clientCode: 'C008',
      company: 'Company H',
      externalId: 'EXT008',
      surname: 'Wilson',
      firstName: 'Jessica',
      dateOfBirth: '1979-05-11',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7905110915080',
      age: 44,
      drivingLicenceIssueDate: '1998-08-24',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class H',
      lastInteractionDate: '2023-08-24'
    },
    {
      entityId: 9,
      clientCode: 'C009',
      company: 'Company I',
      externalId: 'EXT009',
      surname: 'Brown',
      firstName: 'Robert',
      dateOfBirth: '1986-03-17',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8603170456089',
      age: 37,
      drivingLicenceIssueDate: '2004-02-10',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class I',
      lastInteractionDate: '2023-02-10'
    },
    {
      entityId: 10,
      clientCode: 'C010',
      company: 'Company J',
      externalId: 'EXT010',
      surname: 'White',
      firstName: 'Jennifer',
      dateOfBirth: '1990-09-13',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9009130014087',
      age: 33,
      drivingLicenceIssueDate: '2009-05-14',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class J',
      lastInteractionDate: '2023-05-14'
    },
    {
      entityId: 11,
      clientCode: 'C011',
      company: 'Company K',
      externalId: 'EXT011',
      surname: 'Moore',
      firstName: 'William',
      dateOfBirth: '1978-10-23',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7810235204082',
      age: 45,
      drivingLicenceIssueDate: '1996-12-07',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class K',
      lastInteractionDate: '2023-12-07'
    },
    {
      entityId: 12,
      clientCode: 'C012',
      company: 'Company L',
      externalId: 'EXT012',
      surname: 'Taylor',
      firstName: 'Linda',
      dateOfBirth: '1982-04-09',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8204095493080',
      age: 41,
      drivingLicenceIssueDate: '2000-07-30',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class L',
      lastInteractionDate: '2023-07-30'
    },
    {
      entityId: 13,
      clientCode: 'C013',
      company: 'Company M',
      externalId: 'EXT013',
      surname: 'Anderson',
      firstName: 'David',
      dateOfBirth: '1979-06-14',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7906140209081',
      age: 44,
      drivingLicenceIssueDate: '1998-04-09',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class M',
      lastInteractionDate: '2023-04-09'
    },
    {
      entityId: 14,
      clientCode: 'C014',
      company: 'Company N',
      externalId: 'EXT014',
      surname: 'Thomas',
      firstName: 'Susan',
      dateOfBirth: '1991-03-07',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9103075617083',
      age: 32,
      drivingLicenceIssueDate: '2011-06-06',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class N',
      lastInteractionDate: '2023-06-06'
    },
    {
      entityId: 15,
      clientCode: 'C015',
      company: 'Company O',
      externalId: 'EXT015',
      surname: 'Martinez',
      firstName: 'Charles',
      dateOfBirth: '1988-01-29',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8801295753089',
      age: 35,
      drivingLicenceIssueDate: '2006-09-19',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class O',
      lastInteractionDate: '2023-09-19'
    },
    {
      entityId: 16,
      clientCode: 'C016',
      company: 'Company P',
      externalId: 'EXT016',
      surname: 'Lee',
      firstName: 'Patricia',
      dateOfBirth: '1985-09-28',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8509280141085',
      age: 38,
      drivingLicenceIssueDate: '2003-05-22',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class P',
      lastInteractionDate: '2023-05-22'
    },
    {
      entityId: 17,
      clientCode: 'C017',
      company: 'Company Q',
      externalId: 'EXT017',
      surname: 'Lewis',
      firstName: 'Richard',
      dateOfBirth: '1984-12-17',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8412175222087',
      age: 39,
      drivingLicenceIssueDate: '2002-03-18',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class Q',
      lastInteractionDate: '2023-03-18'
    },
    {
      entityId: 18,
      clientCode: 'C018',
      company: 'Company R',
      externalId: 'EXT018',
      surname: 'Walker',
      firstName: 'Barbara',
      dateOfBirth: '1981-07-13',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8107130984089',
      age: 42,
      drivingLicenceIssueDate: '1999-01-25',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class R',
      lastInteractionDate: '2023-01-25'
    },
    {
      entityId: 19,
      clientCode: 'C019',
      company: 'Company S',
      externalId: 'EXT019',
      surname: 'Hall',
      firstName: 'Joseph',
      dateOfBirth: '1987-05-26',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8705265780086',
      age: 36,
      drivingLicenceIssueDate: '2005-10-21',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class S',
      lastInteractionDate: '2023-10-21'
    },
    {
      entityId: 20,
      clientCode: 'C020',
      company: 'Company T',
      externalId: 'EXT020',
      surname: 'Allen',
      firstName: 'Mary',
      dateOfBirth: '1993-08-05',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9308050542085',
      age: 30,
      drivingLicenceIssueDate: '2011-08-03',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class T',
      lastInteractionDate: '2023-08-03'
    },
    {
      entityId: 21,
      clientCode: 'C021',
      company: 'Company U',
      externalId: 'EXT021',
      surname: 'Young',
      firstName: 'Thomas',
      dateOfBirth: '1985-04-15',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8504155430087',
      age: 38,
      drivingLicenceIssueDate: '2003-02-13',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class U',
      lastInteractionDate: '2023-02-13'
    },
    {
      entityId: 22,
      clientCode: 'C022',
      company: 'Company V',
      externalId: 'EXT022',
      surname: 'Hernandez',
      firstName: 'Nancy',
      dateOfBirth: '1992-05-16',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9205165694088',
      age: 31,
      drivingLicenceIssueDate: '2010-04-27',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class V',
      lastInteractionDate: '2023-04-27'
    },
    {
      entityId: 23,
      clientCode: 'C023',
      company: 'Company W',
      externalId: 'EXT023',
      surname: 'King',
      firstName: 'Daniel',
      dateOfBirth: '1978-06-11',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7806110441083',
      age: 45,
      drivingLicenceIssueDate: '1996-11-05',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class W',
      lastInteractionDate: '2023-11-05'
    },
    {
      entityId: 24,
      clientCode: 'C024',
      company: 'Company X',
      externalId: 'EXT024',
      surname: 'Wright',
      firstName: 'Laura',
      dateOfBirth: '1989-07-16',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8907165266084',
      age: 34,
      drivingLicenceIssueDate: '2007-09-17',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class X',
      lastInteractionDate: '2023-09-17'
    },
    {
      entityId: 25,
      clientCode: 'C025',
      company: 'Company Y',
      externalId: 'EXT025',
      surname: 'Lopez',
      firstName: 'Matthew',
      dateOfBirth: '1991-03-18',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9103185069080',
      age: 32,
      drivingLicenceIssueDate: '2009-07-01',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class Y',
      lastInteractionDate: '2023-07-01'
    },
    {
      entityId: 26,
      clientCode: 'C026',
      company: 'Company Z',
      externalId: 'EXT026',
      surname: 'Hill',
      firstName: 'Sarah',
      dateOfBirth: '1980-01-09',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8001095483087',
      age: 43,
      drivingLicenceIssueDate: '1998-10-30',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class Z',
      lastInteractionDate: '2023-10-30'
    },
    {
      entityId: 27,
      clientCode: 'C027',
      company: 'Company AA',
      externalId: 'EXT027',
      surname: 'Scott',
      firstName: 'Christopher',
      dateOfBirth: '1987-04-15',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8704155177082',
      age: 36,
      drivingLicenceIssueDate: '2005-08-14',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class AA',
      lastInteractionDate: '2023-08-14'
    },
    {
      entityId: 28,
      clientCode: 'C028',
      company: 'Company BB',
      externalId: 'EXT028',
      surname: 'Green',
      firstName: 'Karen',
      dateOfBirth: '1985-05-04',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8505045184085',
      age: 38,
      drivingLicenceIssueDate: '2003-03-22',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class BB',
      lastInteractionDate: '2023-03-22'
    },
    {
      entityId: 29,
      clientCode: 'C029',
      company: 'Company CC',
      externalId: 'EXT029',
      surname: 'Adams',
      firstName: 'Paul',
      dateOfBirth: '1980-03-08',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8003085141087',
      age: 43,
      drivingLicenceIssueDate: '1998-12-15',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class CC',
      lastInteractionDate: '2023-12-15'
    },
    {
      entityId: 30,
      clientCode: 'C030',
      company: 'Company DD',
      externalId: 'EXT030',
      surname: 'Nelson',
      firstName: 'Betty',
      dateOfBirth: '1978-06-19',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '7806195227083',
      age: 45,
      drivingLicenceIssueDate: '1996-05-07',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class DD',
      lastInteractionDate: '2023-05-07'
    },
    {
      entityId: 31,
      clientCode: 'C031',
      company: 'Company EE',
      externalId: 'EXT031',
      surname: 'Mitchell',
      firstName: 'Mark',
      dateOfBirth: '1988-07-21',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8807215058081',
      age: 35,
      drivingLicenceIssueDate: '2006-06-28',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class EE',
      lastInteractionDate: '2023-06-28'
    },
    {
      entityId: 32,
      clientCode: 'C032',
      company: 'Company FF',
      externalId: 'EXT032',
      surname: 'Perez',
      firstName: 'Carol',
      dateOfBirth: '1982-09-07',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8209075253080',
      age: 41,
      drivingLicenceIssueDate: '2000-04-12',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class FF',
      lastInteractionDate: '2023-04-12'
    },
    {
      entityId: 33,
      clientCode: 'C033',
      company: 'Company GG',
      externalId: 'EXT033',
      surname: 'Roberts',
      firstName: 'George',
      dateOfBirth: '1987-01-14',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8701145114083',
      age: 36,
      drivingLicenceIssueDate: '2005-01-18',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class GG',
      lastInteractionDate: '2023-01-18'
    },
    {
      entityId: 34,
      clientCode: 'C034',
      company: 'Company HH',
      externalId: 'EXT034',
      surname: 'Phillips',
      firstName: 'Dorothy',
      dateOfBirth: '1984-03-09',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8403095671089',
      age: 39,
      drivingLicenceIssueDate: '2002-03-06',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class HH',
      lastInteractionDate: '2023-03-06'
    },
    {
      entityId: 35,
      clientCode: 'C035',
      company: 'Company II',
      externalId: 'EXT035',
      surname: 'Turner',
      firstName: 'Jason',
      dateOfBirth: '1992-03-11',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9203115801084',
      age: 31,
      drivingLicenceIssueDate: '2010-09-25',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class II',
      lastInteractionDate: '2023-09-25'
    },
    {
      entityId: 36,
      clientCode: 'C036',
      company: 'Company JJ',
      externalId: 'EXT036',
      surname: 'Campbell',
      firstName: 'Helen',
      dateOfBirth: '1980-02-17',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8002175796082',
      age: 43,
      drivingLicenceIssueDate: '1998-11-19',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class JJ',
      lastInteractionDate: '2023-11-19'
    },
    {
      entityId: 37,
      clientCode: 'C037',
      company: 'Company KK',
      externalId: 'EXT037',
      surname: 'Parker',
      firstName: 'Kevin',
      dateOfBirth: '1983-02-10',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8302105090083',
      age: 40,
      drivingLicenceIssueDate: '2001-06-14',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class KK',
      lastInteractionDate: '2023-06-14'
    },
    {
      entityId: 38,
      clientCode: 'C038',
      company: 'Company LL',
      externalId: 'EXT038',
      surname: 'Evans',
      firstName: 'Donna',
      dateOfBirth: '1990-09-12',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9009125809089',
      age: 33,
      drivingLicenceIssueDate: '2008-05-30',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class LL',
      lastInteractionDate: '2023-05-30'
    },
    {
      entityId: 39,
      clientCode: 'C039',
      company: 'Company MM',
      externalId: 'EXT039',
      surname: 'Edwards',
      firstName: 'Brian',
      dateOfBirth: '1986-02-04',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8602045183080',
      age: 37,
      drivingLicenceIssueDate: '2004-02-03',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class MM',
      lastInteractionDate: '2023-02-03'
    },
    {
      entityId: 40,
      clientCode: 'C040',
      company: 'Company NN',
      externalId: 'EXT040',
      surname: 'Collins',
      firstName: 'Sharon',
      dateOfBirth: '1987-04-11',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8704115222089',
      age: 36,
      drivingLicenceIssueDate: '2005-08-09',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class NN',
      lastInteractionDate: '2023-08-09'
    },
    {
      entityId: 41,
      clientCode: 'C041',
      company: 'Company OO',
      externalId: 'EXT041',
      surname: 'Stewart',
      firstName: 'Edward',
      dateOfBirth: '1993-01-06',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9301065123082',
      age: 30,
      drivingLicenceIssueDate: '2011-01-27',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class OO',
      lastInteractionDate: '2023-01-27'
    },
    {
      entityId: 42,
      clientCode: 'C042',
      company: 'Company PP',
      externalId: 'EXT042',
      surname: 'Sanchez',
      firstName: 'Martha',
      dateOfBirth: '1980-08-24',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8008245803087',
      age: 43,
      drivingLicenceIssueDate: '1998-03-11',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class PP',
      lastInteractionDate: '2023-03-11'
    },
    {
      entityId: 43,
      clientCode: 'C043',
      company: 'Company QQ',
      externalId: 'EXT043',
      surname: 'Morris',
      firstName: 'Patrick',
      dateOfBirth: '1989-04-07',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8904075815088',
      age: 34,
      drivingLicenceIssueDate: '2007-10-07',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class QQ',
      lastInteractionDate: '2023-10-07'
    },
    {
      entityId: 44,
      clientCode: 'C044',
      company: 'Company RR',
      externalId: 'EXT044',
      surname: 'Reed',
      firstName: 'Angela',
      dateOfBirth: '1987-02-05',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8702055448081',
      age: 36,
      drivingLicenceIssueDate: '2005-06-23',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class RR',
      lastInteractionDate: '2023-06-23'
    },
    {
      entityId: 45,
      clientCode: 'C045',
      company: 'Company SS',
      externalId: 'EXT045',
      surname: 'Cook',
      firstName: 'Larry',
      dateOfBirth: '1991-01-08',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9101085092089',
      age: 32,
      drivingLicenceIssueDate: '2009-07-11',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class SS',
      lastInteractionDate: '2023-07-11'
    },
    {
      entityId: 46,
      clientCode: 'C046',
      company: 'Company TT',
      externalId: 'EXT046',
      surname: 'Bailey',
      firstName: 'Sandra',
      dateOfBirth: '1995-06-15',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9506155093085',
      age: 28,
      drivingLicenceIssueDate: '2013-02-20',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class TT',
      lastInteractionDate: '2023-02-20'
    },
    {
      entityId: 47,
      clientCode: 'C047',
      company: 'Company UU',
      externalId: 'EXT047',
      surname: 'Rivera',
      firstName: 'Joshua',
      dateOfBirth: '1984-05-08',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8405085091087',
      age: 39,
      drivingLicenceIssueDate: '2002-11-29',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class UU',
      lastInteractionDate: '2023-11-29'
    },
    {
      entityId: 48,
      clientCode: 'C048',
      company: 'Company VV',
      externalId: 'EXT048',
      surname: 'Miller',
      firstName: 'Rebecca',
      dateOfBirth: '1986-04-01',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8604015231083',
      age: 37,
      drivingLicenceIssueDate: '2004-07-17',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class VV',
      lastInteractionDate: '2023-07-17'
    },
    {
      entityId: 49,
      clientCode: 'C049',
      company: 'Company WW',
      externalId: 'EXT049',
      surname: 'Carter',
      firstName: 'Nathan',
      dateOfBirth: '1993-10-12',
      homeLanguage: 'English',
      maritalStatus: 'Single',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '9310125209080',
      age: 30,
      drivingLicenceIssueDate: '2011-11-20',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class WW',
      lastInteractionDate: '2023-11-20'
    },
    {
      entityId: 50,
      clientCode: 'C050',
      company: 'Company XX',
      externalId: 'EXT050',
      surname: 'Brooks',
      firstName: 'Stephanie',
      dateOfBirth: '1989-11-02',
      homeLanguage: 'English',
      maritalStatus: 'Married',
      maidenName: null,
      nationality: 'South African',
      passportOrId: '8911025843089',
      age: 34,
      drivingLicenceIssueDate: '2007-05-18',
      retirementAge: 65,
      deceased: 'No',
      dateDeceased: null,
      class: 'Class XX',
      lastInteractionDate: '2023-05-18'
    }
  ]);
  